### DISCUSSION TITLE
HTTPS proxy?

### DISCUSSION THREAD

**Discussion by n9yty** [sinamics/ztnet#297] [Ideas]
I was surprised there was no HTTPS proxy in the docker-compose.yml file.

I just borrowed a bit from the ztncui one I had running to get it set up and thought I'd offer it here.

```
version: "3.1"
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztnet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  zerotier:
    image: zyclonite/zerotier:1.12.2
    hostname: zerotier
    container_name: zerotier
    restart: unless-stopped
    volumes:
      - zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - app-network
    ports:
      - "9993:9993/udp"
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=172.31.255.0/29

  ztnet:
    image: sinamics/ztnet:latest
    container_name: ztnet
    working_dir: /app
    volumes:
      - zerotier:/var/lib/zerotier-one
    restart: unless-stopped
      # ports:
      #  - 3000:3000 # Removed these when using the https proxy
      #  - 127.0.0.1:3000:3000  # <--- Use / Uncomment this line to restrict access to localhost only
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztnet
      NEXTAUTH_URL: "https://{YOUR_PUBLIC_HOST_NAME}" # !! Important !! Set the NEXTAUTH_URL environment variable to the canonical URL or IP of your site with port 3000 (if using without proxy) i.e. http://{YOUR_PUBLIC_HOST_NAME}:3000
      NEXTAUTH_SECRET: "random_secret"
    networks:
      - app-network
    expose:
      - "3000"
    links:
      - postgres
    depends_on:
      - postgres
      - zerotier

  https-proxy:
    image: caddy:latest
    container_name: ztnet-https-proxy
    restart: unless-stopped
    depends_on:
      - ztnet
    command: caddy reverse-proxy --from {YOUR-PUBLIC-HOST-NAME} --to ztnet:3000
    volumes:
      - caddy_data:/data
    networks:
      - app-network
    links:
      - ztnet
    ports:
      - "80:80"
      - "443:443"

volumes:
  zerotier:
  postgres-data:
  caddy_data:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/29
```
