### ISSUE TITLE
[Support]: Mismatched PostgreSQL database names in docker-compose.yml sample

### ISSUE THREAD

**Issue by imyller** [sinamics/ztnet#118]
### 📝 Describe the Problem You Are Having

Provided `docker-compose.yml` sample file contains mismatched PostgreSQL database names.

PostgreSQL service container initializes user database `ztnet` while ZTNET service connects and initializes in `postgres` database. This only works because `POSTGRES_USER` is set as `postgres` superuser. 

Both should be `ztnet`.

For the postgres service: https://github.com/sinamics/ztnet/blob/21f176e5e13aea63c457f100c0587888a14407b0/docker-compose.yml#L10

```
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztnet                    <----- correct
```

For the ztnet service: https://github.com/sinamics/ztnet/blob/21f176e5e13aea63c457f100c0587888a14407b0/docker-compose.yml#L51
```
 environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres            <---- should be ztnet
```

### 🔖 Version

0.3.7

### 💻 Operating System

None
