### ISSUE TITLE
[Support]: If using zerotier on the host, how should Docker Compose.yml be configured?

### ISSUE THREAD

**Issue by v808comd** [sinamics/ztnet#153]
### 📝 Describe the Problem You Are Having

I tried to delete the paragraph 'zerotier:'. And, change the 'ztnet:' paragraph

Volumes:
-/var/lib/zerotier one:/var/lib/zerotier one
Network_ Mode: host

'Docker compose up - d' will prompt me that the directory is read-only

### 🔖 Version

0.3.9

### 💻 Operating System

None

**Comment by v808comd** [comment]
Doing so may make the IPv6 address of the planet valid

**Comment by sinamics** [comment]
I tested this myself and it worked. 
i Changed the docker-composer as showed bellow, and you also need to change the zerotier url in admin menu to use localhost instead of zerotier hostname.

![image](https://github.com/sinamics/ztnet/assets/7771916/dda27e73-218f-4fce-b841-53acd20b4653)


docker-compose.yml:
```yml
version: "3.1"
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztnet
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
#    networks:
#      - app-network

#  zerotier:
#    image: zyclonite/zerotier:1.10.6
#    hostname: zerotier
#    container_name: zerotier
#    restart: unless-stopped
#    volumes:
#      - zerotier:/var/lib/zerotier-one
#    cap_add:
#      - NET_ADMIN
#      - SYS_ADMIN
#    devices:
#      - /dev/net/tun:/dev/net/tun
#    networks:
#      - app-network
#    ports:
#      - "9993:9993/udp"
#    environment:
#      - ZT_OVERRIDE_LOCAL_CONF=true
#      - ZT_ALLOW_MANAGEMENT_FROM=172.31.255.0/29

  ztnet:
    image: sinamics/ztnet
    network_mode: host
    container_name: ztnet
    working_dir: /app
    volumes:
      - /var/lib/zerotier-one:/var/lib/zerotier-one
    restart: unless-stopped
#    ports:
#      - 3000:3000
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      NEXTAUTH_URL: "http://localhost:3000"
      NEXTAUTH_SECRET: "random_secret"
#    networks:
#      - app-network
#    links:
#      - postgres
    depends_on:
      - postgres
#      - zerotier
volumes:
  zerotier:
  postgres-data:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/29
```


If you get permission errors, then make sure docker are able to read the /var/lib/zerotier-one folder
