### ISSUE TITLE
[Support]: Access to the controller within the zerotier network

### ISSUE THREAD

**Issue by dsm150** [sinamics/ztnet#281]
### 📝 Inquiry

I created a network on the controller, added my laptop to it, and also connected the controller itself to this network. I can ping the zt ip address of the controller from my laptop without any problems, but the web panel of the controller does not open at the same address. Like http://zt_ip_of_controller:3000

In the configuration file, of course, I indicated - Allow Management From:
0.0.0.0/0

### 🔖 Version

0.5.8

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### 💻 Operating System

None

**Comment by sinamics** [comment]
This will probably not work as ztnet is running in a diffrent container than zerotier, and zt virtual adapter does not talk with the app-network used between containers. I belive you would need to configure routing from zt to app-network

**Comment by dsm150** [comment]
> I belive you would need to configure routing from zt to app-network 
> 
> 

You mean add route in ZT network settings on controller?

**Comment by sinamics** [comment]
Assign the zerotier container to host network like this:
```yml
  zerotier:
    image: zyclonite/zerotier:1.12.2
    hostname: zerotier
    container_name: zerotier
    network_mode: host     # < -- Add network mode to host
    restart: unless-stopped
    volumes:
      - zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
   # networks:     < -- comment out
   #   - app-network      < -- comment out
   # ports:    < -- comment out 
   #   - "9993:9993/udp"   < -- comment out
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=0.0.0.0/0
 ```
 
 You also need to update `NEXTAUTH_URL` in ztnet.
 ```yml
 NEXTAUTH_URL: "http://zt_ip:3000"
 ```
 
 Now run `docker-compose up -d` to restart zt container. 
 You should now be able to reach ztnet web ui using the zt `<ip:3000>` address of the controller. 
 
 Note!, this only works if you map ztnet ports like this and not to the loopback interface.
 ```yml
     ports:
      - 3000:3000
 ```

**Comment by dsm150** [comment]
After changes, i have this:

APIError: An error occurred fetching data from http://zerotier:9993/controller/network/27c79da1c336db/member
Verify that the ZeroTier container is operational
If other instances of ZeroTier are active locally, please deactivate them as it might cause conflicts.

in web interface

**Comment by sinamics** [comment]
yeah, i forgot to say you need to change the Local Zerotier URL in admin => controller page to `http://your_server_ip:9993`

**Comment by dsm150** [comment]
> You also need to update `NEXTAUTH_URL` in ztnet.

If I specify an address from the zt network, do I lose the ability to access the host system address?

What if I want to provide access to the controller to clients from different zt networks? How to be in this case?

**Comment by dsm150** [comment]
Reporting
I left the IP address of the host system in the NEXTAUTH_URL line.
in admin => controller page also indicated the address of the host system.
Now the controller panel is available both at the system host address and at the controller address at the ZT network

One more question
Will the changes made to the configuration file prevent further updates?

**Comment by sinamics** [comment]
> I left the IP address of the host system in the NEXTAUTH_URL line.

What happens when you logout of ztnet? does it redirect correctly to the login page with zt ip?

> One more question
Will the changes made to the configuration file prevent further updates?

No, changes to the docker-composer file will not prevent application updates.

**Comment by dsm150** [comment]
I didn't quite understand the question.
At the moment, I am simultaneously logged in from a computer located on the same local network as the controller and from a laptop via the ZT network

**Comment by sinamics** [comment]
When you using `http://zt_ip:3000` to access ztnet, what happens when you press the "Logout" button in the sidebar. Does the application correctly redirects you to the `http://zt_ip:3000/auth/login` page, or the `http://host_ip:3000/auth/login` ?

ztnet uses `NEXTAUTH_URL` to handle the internal redirects, e.g when a user logout.

**Comment by dsm150** [comment]
It redirects to http://host_ip:3000/auth/login

**Comment by sinamics** [comment]
Try adding `AUTH_TRUST_HOST: "true"` to ztnet container. 
```yml
  ztnet:
    image: sinamics/ztnet:latest
    environment:
      ....
      NEXTAUTH_URL: "http://server_ip:3000"
      AUTH_TRUST_HOST: "true"
      ....
  ```
Now it should redirect using the url hostname instead of `NEXTAUTH_URL`.
