### ISSUE TITLE
[Support]: What's the volume mount for?

### ISSUE THREAD

**Issue by Slyke** [sinamics/ztnet#323]
### 📝 Inquiry

It seems everything is stored in the database, is there any reason to keep the volume mount?

### 🔖 Version

v0.5.10

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### 💻 Operating System

Debian

**Comment by Slyke** [comment]
Reason I ask is because I want to spawn multiple instances of ztnet, on different ports with different `NEXTAUTH_URL`s. Having `NEXTAUTH_URL` default to `$Protocol://$IP:$Port` if it is not set would be good as well.

This way it can be access from LAN and also from ZeroTier, without specifying a new volume for each network:

```
  ztnet-zt:
    image: sinamics/ztnet:0.5.10
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ztnet
      POSTGRES_USER: ztnetuser
      POSTGRES_PASSWORD: XXXXXXXXXXX
      NEXTAUTH_SECRET: YYYYYYYYYYY
      # Run `docker exec -it $(docker ps | grep zerotier-controller | head -n 1 | cut -d ' ' -f1) cat /var/lib/zerotier-one/authtoken.secret` while the container is running to get the secret.
      # This can also be entered in the web interface.
      # ZT_SECRET: ZT_CONTROLLER_SECRET.
      NEXTAUTH_URL: "http://172.25.25.10:3000" #ZT Network
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

  ztnet-lan:
    image: sinamics/ztnet:0.5.10
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: ztnet
      POSTGRES_USER: ztnetuser
      POSTGRES_PASSWORD: XXXXXXXXXXX
      NEXTAUTH_SECRET: YYYYYYYYYYY
      # Run `docker exec -it $(docker ps | grep zerotier-controller | head -n 1 | cut -d ' ' -f1) cat /var/lib/zerotier-one/authtoken.secret` while the container is running to get the secret.
      # This can also be entered in the web interface.
      # ZT_SECRET: ZT_CONTROLLER_SECRET.
      NEXTAUTH_URL: "http://192.168.1.250:3001" # Local
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - app-network

```
