### ISSUE TITLE
[Support]: ZTNET container exits with code 0

### ISSUE THREAD

**Issue by fuyukihidekii** [sinamics/ztnet#440]
### 📝 Inquiry

Hi there, ZTNET container exits with code 0 while interacting with the web interface and restarts on its own. However if i let it running w/o interacting with the web UI, it does keep running. There's no other zerotier program running either in the host or in containers.

I did changed the postgres user and password before running it for the first time, but i believe that this is not causing the problem.

I would like to know if is there any other information or debug step that i can follow to properly report this.

### 🔖 Version

v0.6.6

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### 💻 Operating System

Other Linux

### 📚 Any Other Information That May Be Helpful

I have attached a log, my docker-compose.yml and information about my system / docker/ hardware.

<details><summary>/etc/os-release</summary>
<p>

```
NAME="openSUSE Tumbleweed"
# VERSION="20240612"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20240612"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
# CPE 2.3 format, boo#1217921
CPE_NAME="cpe:2.3:o:opensuse:tumbleweed:20240612:*:*:*:*:*:*:*"
#CPE 2.2 format
#CPE_NAME="cpe:/o:opensuse:tumbleweed:20240612"
BUG_REPORT_URL="https://bugzilla.opensuse.org"
SUPPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
LOGO="distributor-logo-Tumbleweed"
```

</p>
</details> 

<details><summary>neofetch</summary>
<p>

```
                                     ......            fuyukihidekii@RV415 
     .,cdxxxoc,.               .:kKMMMNWMMMNk:.        ---------------- 
    cKMMN0OOOKWMMXo. A        ;0MWk:'      ':OMMk.     OS: openSUSE Tumbleweed x86_64 
  ;WMK;'       'lKMMNM,     :NMK'             'OMW;    Host: RV415 P07RAT 
 cMW;             WMMMN   ,XMK'                 oMM.   Kernel: 6.9.3-1-default 
.MMc             ''^*~l. xMN:                    KM0   Uptime: 56 mins 
'MM.                   .NMO                      oMM   Packages: 2410 (rpm) 
.MM,                 .kMMl                       xMN   Shell: bash 5.2.26 
 KM0               .kMM0' .dl>~,.               .WMd   Resolution: 1366x768 
 'XM0.           ,OMMK'    OMMM7'              .XMK    DE: Plasma 6.0.5 
   *WMO:.    .;xNMMk'       NNNMKl.          .xWMx     WM: KWin 
     ^ONMMNXMMMKx;          V  'xNMWKkxllox0NMWk'      Theme: Breeze [GTK2/3] 
         '''''                    ':dOOXXKOxl'         Icons: breeze [GTK2/3] 
                                                       Terminal: konsole 
                                                       CPU: AMD E-300 APU (2) @ 1.300GHz 
                                                       GPU: AMD ATI Radeon HD 6310 
                                                       Memory: 2678MiB / 7775MiB
``` 

</p>
</details> 

<details><summary>docker-compose.yml</summary>
<p>

```
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: RV415
      POSTGRES_PASSWORD: [redacted-for-support-post]
      POSTGRES_DB: ztnet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  zerotier:
    image: zyclonite/zerotier:1.14.0
    hostname: zerotier
    container_name: zerotier
    restart: unless-stopped
    volumes:
      - zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - app-network
    ports:
      - "9993:9993/udp"
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=172.31.255.0/29

  ztnet:
    image: sinamics/ztnet:latest
    container_name: ztnet
    working_dir: /app
    volumes:
      - zerotier:/var/lib/zerotier-one
    restart: unless-stopped
    ports:
      - 3000:3000
    # - 127.0.0.1:3000:3000  <--- Use / Uncomment this line to restrict access to localhost only
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: RV415
      POSTGRES_PASSWORD: [redacted-for-support-post]
      POSTGRES_DB: ztnet
      NEXTAUTH_URL: "http://192.168.3.5:3000" # !! Important !! Set the NEXTAUTH_URL environment variable to the canonical URL or IP of your site with port 3000
      NEXTAUTH_SECRET: "random_secret"
      NEXTAUTH_URL_INTERNAL: "http://ztnet:3000" # Internal NextAuth URL for 'ztnet' container on port 3000. Do not change unless modifying container name.
    networks:
      - app-network
    links:
      - postgres
    depends_on:
      - postgres
      - zerotier

  ############################################################################
  #                                                                          #
  # Uncomment the section below to enable HTTPS reverse proxy with Caddy.    #
  #                                                                          #
  # Steps:                                                                   #
  # 1. Replace <YOUR-PUBLIC-HOST-NAME> with your actual public domain name.  #
  # 2. Uncomment the caddy_data volume definition in the volumes section.    #
  #                                                                          #
  ############################################################################

  # https-proxy:
  #   image: caddy:latest
  #   container_name: ztnet-https-proxy
  #   restart: unless-stopped
  #   depends_on:
  #     - ztnet
  #   command: caddy reverse-proxy --from <YOUR-PUBLIC-HOST-NAME> --to ztnet:3000
  #   volumes:
  #     - caddy_data:/data
  #   networks:
  #     - app-network
  #   links:
  #     - ztnet
  #   ports:
  #     - "80:80"
  #     - "443:443"

volumes:
  zerotier:
  postgres-data:
  # caddy_data:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/29
```

</p>
</details> 

<details><summary>docker compose ps -a</summary>
<p>

```
NAME       IMAGE                       COMMAND                  SERVICE    CREATED             STATUS          PORTS
postgres   postgres:15.2-alpine        "docker-entrypoint.s…"   postgres   About an hour ago   Up 37 minutes   5432/tcp
zerotier   zyclonite/zerotier:1.14.0   "entrypoint.sh -U"       zerotier   About an hour ago   Up 37 minutes   0.0.0.0:9993->9993/udp, :::9993->9993/udp
ztnet      sinamics/ztnet:latest       "/app/init-db.sh nod…"   ztnet      About an hour ago   Up 26 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp
```

</p>
</details> 

<details><summary>docker compose logs -f -t</summary>
<p>

```
zerotier  | 2024-06-13T16:23:57.305068953Z Starting Control Plane...
zerotier  | 2024-06-13T16:23:57.305213035Z Starting V6 Control Plane...
ztnet     | 2024-06-13T16:24:00.433346314Z Creating .env file...
ztnet     | 2024-06-13T16:24:00.762188793Z Applying migrations to the database...
ztnet     | 2024-06-13T16:24:08.859648713Z Environment variables loaded from .env
ztnet     | 2024-06-13T16:24:08.865541121Z Prisma schema loaded from prisma/schema.prisma
ztnet     | 2024-06-13T16:24:08.928066023Z Datasource "db": PostgreSQL database "ztnet", schema "public" at "postgres:5432"
ztnet     | 2024-06-13T16:24:09.575880438Z
ztnet     | 2024-06-13T16:24:09.576054556Z 31 migrations found in prisma/migrations
ztnet     | 2024-06-13T16:24:09.576083521Z
ztnet     | 2024-06-13T16:24:10.000953943Z
ztnet     | 2024-06-13T16:24:10.004674997Z No pending migrations to apply.
ztnet     | 2024-06-13T16:24:10.240317009Z npm notice
ztnet     | 2024-06-13T16:24:10.240462885Z npm notice New minor version of npm available! 10.7.0 -> 10.8.1
ztnet     | 2024-06-13T16:24:10.240494076Z npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.1
ztnet     | 2024-06-13T16:24:10.240521859Z npm notice To update run: npm install -g npm@10.8.1
ztnet     | 2024-06-13T16:24:10.240548384Z npm notice
ztnet     | 2024-06-13T16:24:10.306219069Z Migrations applied successfully!
ztnet     | 2024-06-13T16:24:10.306370497Z Seeding the database...
ztnet     | 2024-06-13T16:24:16.734777152Z Environment variables loaded from .env
ztnet     | 2024-06-13T16:24:16.741144481Z Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...
postgres  | 2024-06-13T16:23:55.939774562Z
postgres  | 2024-06-13T16:23:55.939916198Z PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres  | 2024-06-13T16:23:55.939984908Z
postgres  | 2024-06-13T16:23:56.626313915Z 2024-06-13 16:23:56.624 UTC [1] LOG:  starting PostgreSQL 15.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r4) 12.2.1 20220924, 64-bit
postgres  | 2024-06-13T16:23:56.626408043Z 2024-06-13 16:23:56.625 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres  | 2024-06-13T16:23:56.626437108Z 2024-06-13 16:23:56.625 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres  | 2024-06-13T16:23:57.081640475Z 2024-06-13 16:23:57.079 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres  | 2024-06-13T16:23:57.383224856Z 2024-06-13 16:23:57.379 UTC [23] LOG:  database system was shut down at 2024-06-13 16:23:23 UTC
postgres  | 2024-06-13T16:23:57.509755610Z 2024-06-13 16:23:57.508 UTC [1] LOG:  database system is ready to accept connections
ztnet     | 2024-06-13T16:24:26.273975571Z Seeding:: User Options complete!
ztnet     | 2024-06-13T16:24:26.646310308Z Seeding:: Updating user ID complete!
ztnet     | 2024-06-13T16:24:26.760930368Z
ztnet     | 2024-06-13T16:24:26.761125508Z 🌱  The seed command has been executed.
ztnet     | 2024-06-13T16:24:27.357267932Z Database seeded successfully!
ztnet     | 2024-06-13T16:24:27.357462859Z Executing command
ztnet     | 2024-06-13T16:24:29.685317419Z    ▲ Next.js 14.1.4
ztnet     | 2024-06-13T16:24:29.687729845Z    - Local:        http://aec652dcb7d1:3000
ztnet     | 2024-06-13T16:24:29.688669647Z    - Network:      http://172.31.255.4:3000
ztnet     | 2024-06-13T16:24:29.689451823Z
ztnet     | 2024-06-13T16:24:30.551591518Z  ✓ Ready in 925ms
ztnet exited with code 0
ztnet     | 2024-06-13T16:25:18.622342140Z Applying migrations to the database...
ztnet     | 2024-06-13T16:25:24.653094542Z Environment variables loaded from .env
ztnet     | 2024-06-13T16:25:24.657397810Z Prisma schema loaded from prisma/schema.prisma
ztnet     | 2024-06-13T16:25:24.697597344Z Datasource "db": PostgreSQL database "ztnet", schema "public" at "postgres:5432"
ztnet     | 2024-06-13T16:25:25.158588672Z
ztnet     | 2024-06-13T16:25:25.160392614Z 31 migrations found in prisma/migrations
ztnet     | 2024-06-13T16:25:25.160772241Z
ztnet     | 2024-06-13T16:25:25.486803250Z
ztnet     | 2024-06-13T16:25:25.491542817Z No pending migrations to apply.
ztnet     | 2024-06-13T16:25:25.706706091Z Migrations applied successfully!
ztnet     | 2024-06-13T16:25:25.707875542Z Seeding the database...
ztnet     | 2024-06-13T16:25:31.509290339Z Environment variables loaded from .env
ztnet     | 2024-06-13T16:25:31.515643313Z Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...
ztnet     | 2024-06-13T16:25:38.244351110Z Seeding:: User Options complete!
ztnet     | 2024-06-13T16:25:38.524026250Z Seeding:: Updating user ID complete!
ztnet     | 2024-06-13T16:25:38.599097222Z
ztnet     | 2024-06-13T16:25:38.599292235Z 🌱  The seed command has been executed.
ztnet     | 2024-06-13T16:25:38.906486234Z Database seeded successfully!
ztnet     | 2024-06-13T16:25:38.906603562Z Executing command
ztnet     | 2024-06-13T16:25:40.386974869Z    ▲ Next.js 14.1.4
ztnet     | 2024-06-13T16:25:40.390151851Z    - Local:        http://aec652dcb7d1:3000
ztnet     | 2024-06-13T16:25:40.390309382Z    - Network:      http://172.31.255.4:3000
ztnet     | 2024-06-13T16:25:40.391884103Z
ztnet     | 2024-06-13T16:25:41.231344354Z  ✓ Ready in 904ms
postgres  | 2024-06-13T16:28:57.470210425Z 2024-06-13 16:28:57.469 UTC [21] LOG:  checkpoint starting: time
postgres  | 2024-06-13T16:29:00.139039012Z 2024-06-13 16:29:00.138 UTC [21] LOG:  checkpoint complete: wrote 18 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.414 s, sync=0.884 s, total=2.670 s; sync files=11, longest=0.222 s, average=0.081 s; distance=68 kB, estimate=68 kB
ztnet exited with code 0
ztnet     | 2024-06-13T16:30:31.850033009Z Applying migrations to the database...
ztnet     | 2024-06-13T16:30:38.460963796Z Environment variables loaded from .env
ztnet     | 2024-06-13T16:30:38.464646051Z Prisma schema loaded from prisma/schema.prisma
ztnet     | 2024-06-13T16:30:38.511522471Z Datasource "db": PostgreSQL database "ztnet", schema "public" at "postgres:5432"
ztnet     | 2024-06-13T16:30:38.978300911Z
ztnet     | 2024-06-13T16:30:38.979152865Z 31 migrations found in prisma/migrations
ztnet     | 2024-06-13T16:30:38.979283921Z
ztnet     | 2024-06-13T16:30:39.306581071Z
ztnet     | 2024-06-13T16:30:39.307801568Z No pending migrations to apply.
ztnet     | 2024-06-13T16:30:39.532928853Z Migrations applied successfully!
ztnet     | 2024-06-13T16:30:39.533057566Z Seeding the database...
ztnet     | 2024-06-13T16:30:46.850686181Z Environment variables loaded from .env
ztnet     | 2024-06-13T16:30:46.861191216Z Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...
ztnet     | 2024-06-13T16:30:54.422663146Z Seeding:: User Options complete!
ztnet     | 2024-06-13T16:30:54.709325010Z Seeding:: Updating user ID complete!
ztnet     | 2024-06-13T16:30:54.790301560Z
ztnet     | 2024-06-13T16:30:54.790546715Z 🌱  The seed command has been executed.
ztnet     | 2024-06-13T16:30:55.083449950Z Database seeded successfully!
ztnet     | 2024-06-13T16:30:55.083811392Z Executing command
ztnet     | 2024-06-13T16:30:56.548953867Z    ▲ Next.js 14.1.4
ztnet     | 2024-06-13T16:30:56.551265703Z    - Local:        http://aec652dcb7d1:3000
ztnet     | 2024-06-13T16:30:56.551388784Z    - Network:      http://172.31.255.4:3000
ztnet     | 2024-06-13T16:30:56.552751844Z
ztnet     | 2024-06-13T16:30:57.402337522Z  ✓ Ready in 912ms
postgres  | 2024-06-13T16:33:57.239684763Z 2024-06-13 16:33:57.238 UTC [21] LOG:  checkpoint starting: time
postgres  | 2024-06-13T16:34:00.503993048Z 2024-06-13 16:34:00.501 UTC [21] LOG:  checkpoint complete: wrote 19 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.823 s, sync=1.045 s, total=3.263 s; sync files=14, longest=0.286 s, average=0.075 s; distance=79 kB, estimate=79 kB
ztnet exited with code 0
ztnet     | 2024-06-13T16:37:46.652067113Z Applying migrations to the database...
ztnet     | 2024-06-13T16:37:54.152474100Z Environment variables loaded from .env
ztnet     | 2024-06-13T16:37:54.157103283Z Prisma schema loaded from prisma/schema.prisma
ztnet     | 2024-06-13T16:37:54.231753445Z Datasource "db": PostgreSQL database "ztnet", schema "public" at "postgres:5432"
postgres  | 2024-06-13T16:37:54.682906356Z 2024-06-13 16:37:54.678 UTC [99] LOG:  could not receive data from client: Connection reset by peer
ztnet     | 2024-06-13T16:37:54.797089033Z
ztnet     | 2024-06-13T16:37:54.797211826Z 31 migrations found in prisma/migrations
ztnet     | 2024-06-13T16:37:54.797240030Z
ztnet     | 2024-06-13T16:37:55.168075943Z
ztnet     | 2024-06-13T16:37:55.171921267Z No pending migrations to apply.
ztnet     | 2024-06-13T16:37:55.621711220Z Migrations applied successfully!
ztnet     | 2024-06-13T16:37:55.623419118Z Seeding the database...
ztnet     | 2024-06-13T16:38:02.687954673Z Environment variables loaded from .env
ztnet     | 2024-06-13T16:38:02.694633060Z Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...
ztnet     | 2024-06-13T16:38:09.760785756Z Seeding:: User Options complete!
ztnet     | 2024-06-13T16:38:10.054471297Z Seeding:: Updating user ID complete!
ztnet     | 2024-06-13T16:38:10.129022408Z
ztnet     | 2024-06-13T16:38:10.129223257Z 🌱  The seed command has been executed.
ztnet     | 2024-06-13T16:38:10.453067326Z Database seeded successfully!
ztnet     | 2024-06-13T16:38:10.453188662Z Executing command
ztnet     | 2024-06-13T16:38:12.136913481Z    ▲ Next.js 14.1.4
ztnet     | 2024-06-13T16:38:12.138645091Z    - Local:        http://aec652dcb7d1:3000
ztnet     | 2024-06-13T16:38:12.139732292Z    - Network:      http://172.31.255.4:3000
ztnet     | 2024-06-13T16:38:12.140966217Z
ztnet     | 2024-06-13T16:38:12.988664095Z  ✓ Ready in 909ms
postgres  | 2024-06-13T16:38:57.603200193Z 2024-06-13 16:38:57.602 UTC [21] LOG:  checkpoint starting: time
postgres  | 2024-06-13T16:39:00.802313793Z 2024-06-13 16:39:00.801 UTC [21] LOG:  checkpoint complete: wrote 21 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=2.024 s, sync=0.806 s, total=3.200 s; sync files=14, longest=0.174 s, average=0.058 s; distance=79 kB, estimate=79 kB
ztnet exited with code 0
ztnet     | 2024-06-13T16:40:22.249850553Z Applying migrations to the database...
ztnet     | 2024-06-13T16:40:28.307125036Z Environment variables loaded from .env
ztnet     | 2024-06-13T16:40:28.311188032Z Prisma schema loaded from prisma/schema.prisma
ztnet     | 2024-06-13T16:40:28.341148098Z Datasource "db": PostgreSQL database "ztnet", schema "public" at "postgres:5432"
postgres  | 2024-06-13T16:40:28.716486659Z 2024-06-13 16:40:28.714 UTC [118] LOG:  could not receive data from client: Connection reset by peer
ztnet     | 2024-06-13T16:40:28.794100435Z
ztnet     | 2024-06-13T16:40:28.795951549Z 31 migrations found in prisma/migrations
ztnet     | 2024-06-13T16:40:28.796863723Z
ztnet     | 2024-06-13T16:40:29.128650298Z
ztnet     | 2024-06-13T16:40:29.132868231Z No pending migrations to apply.
postgres  | 2024-06-13T16:40:29.139187215Z 2024-06-13 16:40:29.136 UTC [119] LOG:  could not receive data from client: Connection reset by peer
ztnet     | 2024-06-13T16:40:29.479958691Z Migrations applied successfully!
ztnet     | 2024-06-13T16:40:29.481011720Z Seeding the database...
ztnet     | 2024-06-13T16:40:35.848831689Z Environment variables loaded from .env
ztnet     | 2024-06-13T16:40:35.855534376Z Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...
ztnet     | 2024-06-13T16:40:42.848031681Z Seeding:: User Options complete!
ztnet     | 2024-06-13T16:40:43.130943989Z Seeding:: Updating user ID complete!
ztnet     | 2024-06-13T16:40:43.212275608Z
ztnet     | 2024-06-13T16:40:43.212460556Z 🌱  The seed command has been executed.
ztnet     | 2024-06-13T16:40:43.611959860Z Database seeded successfully!
ztnet     | 2024-06-13T16:40:43.612093194Z Executing command
ztnet     | 2024-06-13T16:40:45.374948238Z    ▲ Next.js 14.1.4
ztnet     | 2024-06-13T16:40:45.377078994Z    - Local:        http://aec652dcb7d1:3000
ztnet     | 2024-06-13T16:40:45.378295212Z    - Network:      http://172.31.255.4:3000
ztnet     | 2024-06-13T16:40:45.378445994Z
ztnet     | 2024-06-13T16:40:46.310011491Z  ✓ Ready in 994ms
ztnet exited with code 0
ztnet     | 2024-06-13T16:41:21.950238317Z Applying migrations to the database...
ztnet     | 2024-06-13T16:41:29.455596535Z Environment variables loaded from .env
ztnet     | 2024-06-13T16:41:29.460290609Z Prisma schema loaded from prisma/schema.prisma
ztnet     | 2024-06-13T16:41:29.505686368Z Datasource "db": PostgreSQL database "ztnet", schema "public" at "postgres:5432"
ztnet     | 2024-06-13T16:41:29.981458761Z
ztnet     | 2024-06-13T16:41:29.983130013Z 31 migrations found in prisma/migrations
ztnet     | 2024-06-13T16:41:29.984060729Z
ztnet     | 2024-06-13T16:41:30.377977801Z
ztnet     | 2024-06-13T16:41:30.393499197Z No pending migrations to apply.
ztnet     | 2024-06-13T16:41:31.084107908Z Migrations applied successfully!
ztnet     | 2024-06-13T16:41:31.084244079Z Seeding the database...
ztnet     | 2024-06-13T16:41:38.344859416Z Environment variables loaded from .env
ztnet     | 2024-06-13T16:41:38.350944243Z Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...
ztnet     | 2024-06-13T16:41:45.966499941Z Seeding:: User Options complete!
ztnet     | 2024-06-13T16:41:46.258347861Z Seeding:: Updating user ID complete!
ztnet     | 2024-06-13T16:41:46.335860549Z
ztnet     | 2024-06-13T16:41:46.336045474Z 🌱  The seed command has been executed.
ztnet     | 2024-06-13T16:41:46.626462881Z Database seeded successfully!
ztnet     | 2024-06-13T16:41:46.626651936Z Executing command
ztnet     | 2024-06-13T16:41:48.129124807Z    ▲ Next.js 14.1.4
ztnet     | 2024-06-13T16:41:48.132458421Z    - Local:        http://aec652dcb7d1:3000
ztnet     | 2024-06-13T16:41:48.132605904Z    - Network:      http://172.31.255.4:3000
ztnet     | 2024-06-13T16:41:48.134360862Z
ztnet     | 2024-06-13T16:41:48.999578865Z  ✓ Ready in 935ms
```

</p>
</details> 

<details><summary>docker info</summary>
<p>

```
Client:
 Version:    26.1.0-ce
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  0.15.0
    Path:     /usr/lib/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  2.27.1
    Path:     /usr/lib/docker/cli-plugins/docker-compose

Server:
 Containers: 5
  Running: 3
  Paused: 0
  Stopped: 2
 Images: 6
 Server Version: 26.1.0-ce
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2 oci
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3a4de459a68952ffb703bbe7f2290861a75b6b67
 runc version: v1.2.0-rc.1-0-g275e6d85f78a
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.9.3-1-default
 Operating System: openSUSE Tumbleweed
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 7.594GiB
 Name: RV415
 ID: 560a4ec7-a916-4fb6-8887-7daca1a602c0
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

</p>
</details>
