### ISSUE TITLE
[Support]: ZTNET domain user logout changed to ip address

### ISSUE THREAD

**Issue by AnonJervis** [sinamics/ztnet#551]
### 📝 Inquiry

ZTNET is configured with a domain name in the caddy container and was able to load GUI via domain name. However, when I logout, the page address will turn into "ipaddress:3000/auth/login/" instead of "domain/auth/login/". I ran zerotier locally instead of a container. This is the docker-compose.yml:

```
---

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztnet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

#  zerotier:
#   image: zyclonite/zerotier:1.14.0
#    hostname: zerotier
#    container_name: zerotier
#    restart: unless-stopped
#    volumes:
#      - zerotier:/var/lib/zerotier-one
#    cap_add:
#      - NET_ADMIN
#      - SYS_ADMIN
#    devices:
#      - /dev/net/tun:/dev/net/tun
#    networks:
#      - app-network
#    ports:
#      - "9993:9993/udp"
#    environment:
#      - ZT_OVERRIDE_LOCAL_CONF=true
#      - ZT_ALLOW_MANAGEMENT_FROM=172.25.255.0/29

  ztnet:
    image: sinamics/ztnet:latest
    container_name: ztnet
    working_dir: /app
    volumes:
      # - zerotier:/var/lib/zerotier-one
      - /var/lib/zerotier-one:/var/lib/zerotier-one
    restart: unless-stopped
    ports:
      - 3000:3000
    # - 127.0.0.1:3000:3000  <--- Use / Uncomment this line to restrict access to localhost only
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztnet
      NEXTAUTH_URL: "http://ipaddress:3000" # !! Important !! Set the NEXTAUTH_URL environment variable to the canonical URL or IP of your site with port 3000
      NEXTAUTH_SECRET: "secret"
      NEXT_PUBLIC_SITE_NAME: "ZTNET"
      NEXTAUTH_URL_INTERNAL: "http://ztnet:3000" # Internal NextAuth URL for 'ztnet' container on port 3000. Do not change unless modifying container name.
    networks:
      - app-network
    links:
      - postgres
    depends_on:
      - postgres
#      - zerotier

  ############################################################################
  #                                                                          #
  # Uncomment the section below to enable HTTPS reverse proxy with Caddy.    #
  #                                                                          #
  # Steps:                                                                   #
  # 1. Replace <YOUR-PUBLIC-HOST-NAME> with your actual public domain name.  #
  # 2. Uncomment the caddy_data volume definition in the volumes section.    #
  #                                                                          #
  ############################################################################

  https-proxy:
    image: caddy:latest
    container_name: ztnet-https-proxy
    restart: unless-stopped
    depends_on:
      - ztnet
    command: caddy reverse-proxy --from zt.com --to ztnet:3000
    volumes:
      - caddy_data:/data
    networks:
      - app-network
    links:
      - ztnet
    ports:
      - "80:80"
      - "443:443"

volumes:
  zerotier:
  postgres-data:
  caddy_data:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.255.0/29
```

### 🔖 Version

v0.7.0

### 🔧 Deployment Type

- [X] Docker
- [ ] Standalone

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 📚 Any Other Information That May Be Helpful

ztnet container log:

```
Creating .env file...
Applying migrations to the database...
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "ztnet", schema "public" at "postgres:5432"

36 migrations found in prisma/migrations


No pending migrations to apply.
npm notice
npm notice New minor version of npm available! 10.7.0 -> 10.8.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
npm notice To update run: npm install -g npm@10.8.3
npm notice
Migrations applied successfully!
Seeding the database...
Environment variables loaded from .env
Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...
Seeding:: User Options complete!
Seeding:: Updating user ID complete!

🌱  The seed command has been executed.
Database seeded successfully!
Executing command
   ▲ Next.js 14.1.4
   - Local:        http://ipaddress:3000
   - Network:      http://ipaddress:3000

 ✓ Ready in 527ms
Failed to send email notification for new device, check your mail settings.
Socket is initializing
```

caddy ztnet-https-proxy last 7 lines of logs:

```
{"level":"info","ts":1726468835.73813,"logger":"http.acme_client","msg":"authorization finalized","identifier":"zt.com","authz_status":"valid"}
{"level":"info","ts":1726468835.7381673,"logger":"http.acme_client","msg":"validations succeeded; finalizing order","order":"https://acme-v02.api.letsencrypt.org/acme/order/1949130156/305569321646"}
{"level":"info","ts":1726468837.2540607,"logger":"http.acme_client","msg":"got renewal info","names":["zt.com"],"window_start":1731564094.3333333,"window_end":1731736894.3333333,"selected_time":1731708668,"recheck_after":1726490437.2540534,"explanation_url":""}
{"level":"info","ts":1726468837.7070029,"logger":"http.acme_client","msg":"got renewal info","names":["zt.com"],"window_start":1731564094.3333333,"window_end":1731736894.3333333,"selected_time":1731711384,"recheck_after":1726490437.706997,"explanation_url":""}
{"level":"info","ts":1726468837.7070465,"logger":"http.acme_client","msg":"successfully downloaded available certificate chains","count":2,"first_url":"https://acme-v02.api.letsencrypt.org/acme/cert/04c35fba82e5e84d128cf2241dd7125b5f15"}
{"level":"info","ts":1726468837.7075112,"logger":"tls.obtain","msg":"certificate obtained successfully","identifier":"zt.com","issuer":"acme-v02.api.letsencrypt.org-directory"}
{"level":"info","ts":1726468837.7076247,"logger":"tls.obtain","msg":"releasing lock","identifier":"zt.com"}
```
