### ISSUE TITLE
[Support]: Unable to access the web interface from running instance

### ISSUE THREAD

**Issue by AnhDQHE181109** [sinamics/ztnet#635]
### 📝 Inquiry

I've been trying to configure ZTNET in my Alpine installation but after having brought it up using the `docker compose up -d` command, I couldn't really access the web interface using the _NEXTAUTH_URL_ I already configured in the _docker-compose.yml_ file (browser returning connection reset error). 
Looking through ZTNET's logs, I saw that _Next.js_'s network address is actually ZTNET's container ID (I think) but not one belonging to the IP bridge - not sure if that's the cause.

I also did manually check the ZTNET's container's IP to see if it already got assigned an address or not - and it actually did - although it didn't really have any "essential" networking tools such as *ip* or *ifconfig* so I had to check the */proc/net/fib_trie* to check the container's IP address in the IP bridge.

And the Alpine I'm using is actually running inside a QEMU VM - specifically a project that makes running docker on android possible:  [https://github.com/AntonyZ89/docker-qemu-arm](url).  I tried to connect to ZTNET's web interface through SSH port forwarding of the VM and changing _NEXTAUTH_URL_  between *localhost:3000*, *<the VM's ip>:3000*, *<the host's IP>:3000* but to no avail.

I've provided some basic info of the configurations I'm using below (some private info redacted by ***). Is there any other information I can fetch to provide more details? Thanks for your help in advance!

P/s: I'm configuring ZTNET to manage another instance of Zerotier controller running on another machine on my local network, hence the _ZT_ADDR_ and _ZT_SECRET_ variables.

### 🔖 Version

v0.7.3

### 🔧 Deployment Type

- [x] Docker
- [ ] Standalone

### 💻 Operating System

Other Linux

### 🌐 Browser

Edge

### 📚 Any Other Information That May Be Helpful

<details><summary>/etc/os-release</summary>
<p>

```
alpine:~/ztnet# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.21.3
PRETTY_NAME="Alpine Linux v3.21"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

</p>
</details>

<details><summary>docker-compose.yml</summary>
<p>

```
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ***
      POSTGRES_PASSWORD: ***
      POSTGRES_DB: ztnet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  zerotier:
    image: zyclonite/zerotier:1.14.2
    hostname: zerotier
    container_name: zerotier  
    restart: unless-stopped
    volumes:
      - zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - app-network
    ports:
      - "9993:9993/udp"
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
      - ZT_ALLOW_MANAGEMENT_FROM=172.31.255.0/29
      - ZT_ADDR=***
      - ZT_SECRET=***

  ztnet:
    image: sinamics/ztnet:latest
    container_name: ztnet
    working_dir: /app
    volumes:
      - zerotier:/var/lib/zerotier-one
    restart: unless-stopped
    ports:
      - 3000:3000
    # - 127.0.0.1:3000:3000  <--- Use / Uncomment this line to restrict access to localhost only
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ***
      POSTGRES_PASSWORD: ***
      POSTGRES_DB: ztnet
      NEXTAUTH_URL: "http://192.168.50.15:3000" # !! Important !! Set the NEXTAUTH_URL environment variable to the canonical URL or IP of your site with port 3000
      NEXTAUTH_SECRET: "***"
      NEXTAUTH_URL_INTERNAL: "http://ztnet:3000" # Internal NextAuth URL for 'ztnet' container on port 3000. Do not change unless modifying container name.
    networks:
      - app-network
    links:
      - postgres
    depends_on:
      - postgres
      - zerotier

  ############################################################################
  #                                                                          #
  # Uncomment the section below to enable HTTPS reverse proxy with Caddy.    #
  #                                                                          #
  # Steps:                                                                   #
  # 1. Replace <YOUR-PUBLIC-HOST-NAME> with your actual public domain name.  #
  # 2. Uncomment the caddy_data volume definition in the volumes section.    #
  #                                                                          #
  ############################################################################

  # https-proxy:
  #   image: caddy:latest
  #   container_name: ztnet-https-proxy
  #   restart: unless-stopped
  #   depends_on:
  #     - ztnet
  #   command: caddy reverse-proxy --from <YOUR-PUBLIC-HOST-NAME> --to ztnet:3000
  #   volumes:
  #     - caddy_data:/data
  #   networks:
  #     - app-network
  #   links:
  #     - ztnet
  #   ports:
  #     - "80:80"
  #     - "443:443"

volumes:
  zerotier:
  postgres-data:
  # caddy_data:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/29
```

</p>
</details>

<details><summary>docker ps</summary>
<p>

```
CONTAINER ID   IMAGE                       COMMAND                  CREATED       STATUS          PORTS                                       NAMES
68ad58ca71aa   zyclonite/zerotier:1.14.2   "entrypoint.sh -U"       2 hours ago   Up 37 minutes   0.0.0.0:9993->9993/udp, :::9993->9993/udp   zerotier
d43cf77aac64   sinamics/ztnet:latest       "/app/init-db.sh nod…"   3 hours ago   Up 59 minutes   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   ztnet
5e65241768de   postgres:15.2-alpine        "docker-entrypoint.s…"   7 hours ago   Up 59 minutes   5432/tcp                                    postgres
```

</p>
</details>

<details><summary>docker logs -f ztnet</summary>
<p>

```
Creating .env file...
Applying migrations to the database...
Environment variables loaded from .env
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "ztnet", schema "public" at "postgres:5432"

38 migrations found in prisma/migrations


No pending migrations to apply.
Migrations applied successfully!
Seeding the database...
Environment variables loaded from .env
Running seed command `ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts` ...
Seeding:: User Options complete!
Seeding:: Updating user ID complete!

🌱  The seed command has been executed.
Database seeded successfully!
Executing command
   ▲ Next.js 15.1.2
   - Local:        http://d43cf77aac64:3000
   - Network:      http://d43cf77aac64:3000

 ✓ Starting...
 ✓ Ready in 15.6s
```

</p>
</details>

<details><summary>docker info</summary>
<p>

```
Client:
 Version:    27.3.1
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.19.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.31.0
    Path:     /usr/libexec/docker/cli-plugins/docker-compose

Server:
 Containers: 4
  Running: 3
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 207ad711eabd375a01713109a8a197d197ff6542
 runc version: 7cb363254b69e10320360b63fb73e0ffb5da7bf2
 init version:
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.12.17-0-virt
 Operating System: Alpine Linux v3.21
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 966.3MiB
 Name: alpine
 ID: 9f021b42-774b-4bd5-b815-39345aef318a
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

</p>
</details>
