### ISSUE TITLE
[Support]: ZTNET Login error: "user doesn't exist"

### ISSUE THREAD

**Issue by elvatobarato** [sinamics/ztnet#637]
### 📝 Inquiry

Hi,

After having setup ZTNET on my Synology NAS (which I am trying to use as a ZT controller as well as node), the login page appears and I am unfortunately unable to logon using my working and tested ZT account info. I get a "user doesn't exist" message. 

I am trying to deploy it in Docker using the built-in Synology Container Manager, and after some inital troubleshooting it runs the respective containers without seeming issue. Like mentioned above, I am able to reach the ZTNET login page using my NAS' hostname and port 3000.

According to how I saw it in [another thread](https://github.com/sinamics/ztnet/discussions/254#discussioncomment-7927750), I have modified my docker_compose.yml (called compose.yaml in this case) to use the host network instead of bridge mode, which as I understood, is necessary for the NAS to be both a controller as well as a node. 

Help or leading in the right direction would be greatly appreciated.

```
services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ztnet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  zerotier:
    image: zyclonite/zerotier:1.14.2
    hostname: zerotier
    container_name: zerotier
    restart: unless-stopped
    volumes:
      - zerotier:/var/lib/zerotier-one
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    network_mode: "host"
    #networks:
    #  - app-network
    #ports:
    #  - "9993:9993/udp"
    environment:
      - ZT_OVERRIDE_LOCAL_CONF=true
     # - ZT_ALLOW_MANAGEMENT_FROM=172.31.255.0/29

  ztnet:
    image: sinamics/ztnet:latest
    container_name: ztnet
    working_dir: /app
    volumes:
      - zerotier:/var/lib/zerotier-one
    restart: unless-stopped
    ports:
      - 3000:3000
    # - 127.0.0.1:3000:3000  <--- Use / Uncomment this line to restrict access to localhost only
    environment:
      ZT_ADDR: http://192.168.1.6:9993 
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      NEXTAUTH_URL: "http://myNAShostname3000" # !! Important !! Set the NEXTAUTH_URL environment variable to the canonical URL or IP of your site with port 3000
      NEXTAUTH_SECRET: "random_secret"
      #NEXTAUTH_URL_INTERNAL: "http://ztnet:3000" # Internal NextAuth URL for 'ztnet' container on port 3000. Do not change unless modifying container name.
    networks:
      - app-network
    links:
      - postgres
    depends_on:
      - postgres
      - zerotier

volumes:
  zerotier:
  postgres-data:
  # caddy_data:

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/29
```

### 🔖 Version

v0.7.3

### 🔧 Deployment Type

- [x] Docker
- [ ] Standalone

### 💻 Operating System

Windows

### 🌐 Browser

Firefox
